// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manager.proto

// protoc --go_out=plugins=grpc:. *.proto && sed -i "" -e "s///g" ./*.go

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeInfo struct {
	ProtocolVersion      *NodeInfo_ProtocolVersion `protobuf:"bytes,8,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version"`
	Id                   string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	ListenAddr           string                    `protobuf:"bytes,2,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr"`
	Network              string                    `protobuf:"bytes,3,opt,name=network,proto3" json:"network"`
	Version              string                    `protobuf:"bytes,4,opt,name=version,proto3" json:"version"`
	Channels             string                    `protobuf:"bytes,5,opt,name=channels,proto3" json:"channels"`
	Moniker              string                    `protobuf:"bytes,6,opt,name=moniker,proto3" json:"moniker"`
	Other                *NodeInfo_Other           `protobuf:"bytes,7,opt,name=other,proto3" json:"other"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{0}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetProtocolVersion() *NodeInfo_ProtocolVersion {
	if m != nil {
		return m.ProtocolVersion
	}
	return nil
}

func (m *NodeInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeInfo) GetListenAddr() string {
	if m != nil {
		return m.ListenAddr
	}
	return ""
}

func (m *NodeInfo) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *NodeInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *NodeInfo) GetChannels() string {
	if m != nil {
		return m.Channels
	}
	return ""
}

func (m *NodeInfo) GetMoniker() string {
	if m != nil {
		return m.Moniker
	}
	return ""
}

func (m *NodeInfo) GetOther() *NodeInfo_Other {
	if m != nil {
		return m.Other
	}
	return nil
}

type NodeInfo_ProtocolVersion struct {
	P2P                  string   `protobuf:"bytes,3,opt,name=p2p,proto3" json:"p2p"`
	Block                string   `protobuf:"bytes,1,opt,name=block,proto3" json:"block"`
	App                  string   `protobuf:"bytes,2,opt,name=app,proto3" json:"app"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo_ProtocolVersion) Reset()         { *m = NodeInfo_ProtocolVersion{} }
func (m *NodeInfo_ProtocolVersion) String() string { return proto.CompactTextString(m) }
func (*NodeInfo_ProtocolVersion) ProtoMessage()    {}
func (*NodeInfo_ProtocolVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{0, 0}
}

func (m *NodeInfo_ProtocolVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo_ProtocolVersion.Unmarshal(m, b)
}
func (m *NodeInfo_ProtocolVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo_ProtocolVersion.Marshal(b, m, deterministic)
}
func (m *NodeInfo_ProtocolVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo_ProtocolVersion.Merge(m, src)
}
func (m *NodeInfo_ProtocolVersion) XXX_Size() int {
	return xxx_messageInfo_NodeInfo_ProtocolVersion.Size(m)
}
func (m *NodeInfo_ProtocolVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo_ProtocolVersion.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo_ProtocolVersion proto.InternalMessageInfo

func (m *NodeInfo_ProtocolVersion) GetP2P() string {
	if m != nil {
		return m.P2P
	}
	return ""
}

func (m *NodeInfo_ProtocolVersion) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

func (m *NodeInfo_ProtocolVersion) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

type NodeInfo_Other struct {
	TxIndex              string   `protobuf:"bytes,2,opt,name=tx_index,json=txIndex,proto3" json:"tx_index"`
	RpcAddress           string   `protobuf:"bytes,1,opt,name=rpc_address,json=rpcAddress,proto3" json:"rpc_address"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo_Other) Reset()         { *m = NodeInfo_Other{} }
func (m *NodeInfo_Other) String() string { return proto.CompactTextString(m) }
func (*NodeInfo_Other) ProtoMessage()    {}
func (*NodeInfo_Other) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{0, 1}
}

func (m *NodeInfo_Other) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo_Other.Unmarshal(m, b)
}
func (m *NodeInfo_Other) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo_Other.Marshal(b, m, deterministic)
}
func (m *NodeInfo_Other) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo_Other.Merge(m, src)
}
func (m *NodeInfo_Other) XXX_Size() int {
	return xxx_messageInfo_NodeInfo_Other.Size(m)
}
func (m *NodeInfo_Other) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo_Other.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo_Other proto.InternalMessageInfo

func (m *NodeInfo_Other) GetTxIndex() string {
	if m != nil {
		return m.TxIndex
	}
	return ""
}

func (m *NodeInfo_Other) GetRpcAddress() string {
	if m != nil {
		return m.RpcAddress
	}
	return ""
}

type NetInfoResponse struct {
	Listening            bool                    `protobuf:"varint,4,opt,name=listening,proto3" json:"listening"`
	Listeners            []string                `protobuf:"bytes,1,rep,name=listeners,proto3" json:"listeners"`
	NPeers               string                  `protobuf:"bytes,2,opt,name=n_peers,json=nPeers,proto3" json:"n_peers"`
	Peers                []*NetInfoResponse_Peer `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *NetInfoResponse) Reset()         { *m = NetInfoResponse{} }
func (m *NetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*NetInfoResponse) ProtoMessage()    {}
func (*NetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{1}
}

func (m *NetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetInfoResponse.Unmarshal(m, b)
}
func (m *NetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetInfoResponse.Marshal(b, m, deterministic)
}
func (m *NetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfoResponse.Merge(m, src)
}
func (m *NetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_NetInfoResponse.Size(m)
}
func (m *NetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfoResponse proto.InternalMessageInfo

func (m *NetInfoResponse) GetListening() bool {
	if m != nil {
		return m.Listening
	}
	return false
}

func (m *NetInfoResponse) GetListeners() []string {
	if m != nil {
		return m.Listeners
	}
	return nil
}

func (m *NetInfoResponse) GetNPeers() string {
	if m != nil {
		return m.NPeers
	}
	return ""
}

func (m *NetInfoResponse) GetPeers() []*NetInfoResponse_Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type NetInfoResponse_Peer struct {
	NodeInfo             *NodeInfo                              `protobuf:"bytes,4,opt,name=node_info,json=nodeInfo,proto3" json:"node_info"`
	IsOutbound           bool                                   `protobuf:"varint,1,opt,name=is_outbound,json=isOutbound,proto3" json:"is_outbound"`
	ConnectionStatus     *NetInfoResponse_Peer_ConnectionStatus `protobuf:"bytes,2,opt,name=connection_status,json=connectionStatus,proto3" json:"connection_status"`
	RemoteIp             string                                 `protobuf:"bytes,3,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *NetInfoResponse_Peer) Reset()         { *m = NetInfoResponse_Peer{} }
func (m *NetInfoResponse_Peer) String() string { return proto.CompactTextString(m) }
func (*NetInfoResponse_Peer) ProtoMessage()    {}
func (*NetInfoResponse_Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{1, 0}
}

func (m *NetInfoResponse_Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetInfoResponse_Peer.Unmarshal(m, b)
}
func (m *NetInfoResponse_Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetInfoResponse_Peer.Marshal(b, m, deterministic)
}
func (m *NetInfoResponse_Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfoResponse_Peer.Merge(m, src)
}
func (m *NetInfoResponse_Peer) XXX_Size() int {
	return xxx_messageInfo_NetInfoResponse_Peer.Size(m)
}
func (m *NetInfoResponse_Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfoResponse_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfoResponse_Peer proto.InternalMessageInfo

func (m *NetInfoResponse_Peer) GetNodeInfo() *NodeInfo {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

func (m *NetInfoResponse_Peer) GetIsOutbound() bool {
	if m != nil {
		return m.IsOutbound
	}
	return false
}

func (m *NetInfoResponse_Peer) GetConnectionStatus() *NetInfoResponse_Peer_ConnectionStatus {
	if m != nil {
		return m.ConnectionStatus
	}
	return nil
}

func (m *NetInfoResponse_Peer) GetRemoteIp() string {
	if m != nil {
		return m.RemoteIp
	}
	return ""
}

type NetInfoResponse_Peer_ConnectionStatus struct {
	Duration             string                                           `protobuf:"bytes,4,opt,name=Duration,proto3" json:"Duration"`
	SendMonitor          *NetInfoResponse_Peer_ConnectionStatus_Monitor   `protobuf:"bytes,1,opt,name=SendMonitor,proto3" json:"SendMonitor"`
	RecvMonitor          *NetInfoResponse_Peer_ConnectionStatus_Monitor   `protobuf:"bytes,2,opt,name=RecvMonitor,proto3" json:"RecvMonitor"`
	Channels             []*NetInfoResponse_Peer_ConnectionStatus_Channel `protobuf:"bytes,3,rep,name=Channels,proto3" json:"Channels"`
	XXX_NoUnkeyedLiteral struct{}                                         `json:"-"`
	XXX_unrecognized     []byte                                           `json:"-"`
	XXX_sizecache        int32                                            `json:"-"`
}

func (m *NetInfoResponse_Peer_ConnectionStatus) Reset()         { *m = NetInfoResponse_Peer_ConnectionStatus{} }
func (m *NetInfoResponse_Peer_ConnectionStatus) String() string { return proto.CompactTextString(m) }
func (*NetInfoResponse_Peer_ConnectionStatus) ProtoMessage()    {}
func (*NetInfoResponse_Peer_ConnectionStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{1, 0, 0}
}

func (m *NetInfoResponse_Peer_ConnectionStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus.Unmarshal(m, b)
}
func (m *NetInfoResponse_Peer_ConnectionStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus.Marshal(b, m, deterministic)
}
func (m *NetInfoResponse_Peer_ConnectionStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus.Merge(m, src)
}
func (m *NetInfoResponse_Peer_ConnectionStatus) XXX_Size() int {
	return xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus.Size(m)
}
func (m *NetInfoResponse_Peer_ConnectionStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus proto.InternalMessageInfo

func (m *NetInfoResponse_Peer_ConnectionStatus) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *NetInfoResponse_Peer_ConnectionStatus) GetSendMonitor() *NetInfoResponse_Peer_ConnectionStatus_Monitor {
	if m != nil {
		return m.SendMonitor
	}
	return nil
}

func (m *NetInfoResponse_Peer_ConnectionStatus) GetRecvMonitor() *NetInfoResponse_Peer_ConnectionStatus_Monitor {
	if m != nil {
		return m.RecvMonitor
	}
	return nil
}

func (m *NetInfoResponse_Peer_ConnectionStatus) GetChannels() []*NetInfoResponse_Peer_ConnectionStatus_Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type NetInfoResponse_Peer_ConnectionStatus_Monitor struct {
	Active               bool     `protobuf:"varint,13,opt,name=Active,proto3" json:"Active"`
	Start                string   `protobuf:"bytes,1,opt,name=Start,proto3" json:"Start"`
	Duration             string   `protobuf:"bytes,2,opt,name=Duration,proto3" json:"Duration"`
	Idle                 string   `protobuf:"bytes,3,opt,name=Idle,proto3" json:"Idle"`
	Bytes                string   `protobuf:"bytes,4,opt,name=Bytes,proto3" json:"Bytes"`
	Samples              string   `protobuf:"bytes,5,opt,name=Samples,proto3" json:"Samples"`
	InstRate             string   `protobuf:"bytes,6,opt,name=InstRate,proto3" json:"InstRate"`
	CurRate              string   `protobuf:"bytes,7,opt,name=CurRate,proto3" json:"CurRate"`
	AvgRate              string   `protobuf:"bytes,8,opt,name=AvgRate,proto3" json:"AvgRate"`
	PeakRate             string   `protobuf:"bytes,9,opt,name=PeakRate,proto3" json:"PeakRate"`
	BytesRem             string   `protobuf:"bytes,10,opt,name=BytesRem,proto3" json:"BytesRem"`
	TimeRem              string   `protobuf:"bytes,11,opt,name=TimeRem,proto3" json:"TimeRem"`
	Progress             float64  `protobuf:"fixed64,12,opt,name=Progress,proto3" json:"Progress"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) Reset() {
	*m = NetInfoResponse_Peer_ConnectionStatus_Monitor{}
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) String() string {
	return proto.CompactTextString(m)
}
func (*NetInfoResponse_Peer_ConnectionStatus_Monitor) ProtoMessage() {}
func (*NetInfoResponse_Peer_ConnectionStatus_Monitor) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{1, 0, 0, 0}
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Monitor.Unmarshal(m, b)
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Monitor.Marshal(b, m, deterministic)
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Monitor.Merge(m, src)
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) XXX_Size() int {
	return xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Monitor.Size(m)
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Monitor.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Monitor proto.InternalMessageInfo

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetIdle() string {
	if m != nil {
		return m.Idle
	}
	return ""
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetBytes() string {
	if m != nil {
		return m.Bytes
	}
	return ""
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetSamples() string {
	if m != nil {
		return m.Samples
	}
	return ""
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetInstRate() string {
	if m != nil {
		return m.InstRate
	}
	return ""
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetCurRate() string {
	if m != nil {
		return m.CurRate
	}
	return ""
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetAvgRate() string {
	if m != nil {
		return m.AvgRate
	}
	return ""
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetPeakRate() string {
	if m != nil {
		return m.PeakRate
	}
	return ""
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetBytesRem() string {
	if m != nil {
		return m.BytesRem
	}
	return ""
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetTimeRem() string {
	if m != nil {
		return m.TimeRem
	}
	return ""
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetProgress() float64 {
	if m != nil {
		return m.Progress
	}
	return 0
}

type NetInfoResponse_Peer_ConnectionStatus_Channel struct {
	ID                   float64  `protobuf:"fixed64,5,opt,name=ID,proto3" json:"ID"`
	SendQueueCapacity    string   `protobuf:"bytes,1,opt,name=SendQueueCapacity,proto3" json:"SendQueueCapacity"`
	SendQueueSize        string   `protobuf:"bytes,2,opt,name=SendQueueSize,proto3" json:"SendQueueSize"`
	Priority             string   `protobuf:"bytes,3,opt,name=Priority,proto3" json:"Priority"`
	RecentlySent         string   `protobuf:"bytes,4,opt,name=RecentlySent,proto3" json:"RecentlySent"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) Reset() {
	*m = NetInfoResponse_Peer_ConnectionStatus_Channel{}
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) String() string {
	return proto.CompactTextString(m)
}
func (*NetInfoResponse_Peer_ConnectionStatus_Channel) ProtoMessage() {}
func (*NetInfoResponse_Peer_ConnectionStatus_Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{1, 0, 0, 1}
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Channel.Unmarshal(m, b)
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Channel.Marshal(b, m, deterministic)
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Channel.Merge(m, src)
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) XXX_Size() int {
	return xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Channel.Size(m)
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Channel proto.InternalMessageInfo

func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) GetID() float64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) GetSendQueueCapacity() string {
	if m != nil {
		return m.SendQueueCapacity
	}
	return ""
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) GetSendQueueSize() string {
	if m != nil {
		return m.SendQueueSize
	}
	return ""
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) GetPriority() string {
	if m != nil {
		return m.Priority
	}
	return ""
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) GetRecentlySent() string {
	if m != nil {
		return m.RecentlySent
	}
	return ""
}

type StatusResponse struct {
	Version              string                   `protobuf:"bytes,7,opt,name=version,proto3" json:"version"`
	LatestBlockHash      string                   `protobuf:"bytes,1,opt,name=latest_block_hash,json=latestBlockHash,proto3" json:"latest_block_hash"`
	LatestAppHash        string                   `protobuf:"bytes,2,opt,name=latest_app_hash,json=latestAppHash,proto3" json:"latest_app_hash"`
	LatestBlockHeight    int64                    `protobuf:"varint,3,opt,name=latest_block_height,json=latestBlockHeight,proto3" json:"latest_block_height"`
	LatestBlockTime      string                   `protobuf:"bytes,4,opt,name=latest_block_time,json=latestBlockTime,proto3" json:"latest_block_time"`
	StateHistory         string                   `protobuf:"bytes,5,opt,name=state_history,json=stateHistory,proto3" json:"state_history"`
	TmStatus             *StatusResponse_TmStatus `protobuf:"bytes,6,opt,name=tm_status,json=tmStatus,proto3" json:"tm_status"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{2}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *StatusResponse) GetLatestBlockHash() string {
	if m != nil {
		return m.LatestBlockHash
	}
	return ""
}

func (m *StatusResponse) GetLatestAppHash() string {
	if m != nil {
		return m.LatestAppHash
	}
	return ""
}

func (m *StatusResponse) GetLatestBlockHeight() int64 {
	if m != nil {
		return m.LatestBlockHeight
	}
	return 0
}

func (m *StatusResponse) GetLatestBlockTime() string {
	if m != nil {
		return m.LatestBlockTime
	}
	return ""
}

func (m *StatusResponse) GetStateHistory() string {
	if m != nil {
		return m.StateHistory
	}
	return ""
}

func (m *StatusResponse) GetTmStatus() *StatusResponse_TmStatus {
	if m != nil {
		return m.TmStatus
	}
	return nil
}

type StatusResponse_TmStatus struct {
	NodeInfo             *NodeInfo                              `protobuf:"bytes,3,opt,name=node_info,json=nodeInfo,proto3" json:"node_info"`
	SyncInfo             *StatusResponse_TmStatus_SyncInfo      `protobuf:"bytes,1,opt,name=sync_info,json=syncInfo,proto3" json:"sync_info"`
	ValidatorInfo        *StatusResponse_TmStatus_ValidatorInfo `protobuf:"bytes,2,opt,name=validator_info,json=validatorInfo,proto3" json:"validator_info"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *StatusResponse_TmStatus) Reset()         { *m = StatusResponse_TmStatus{} }
func (m *StatusResponse_TmStatus) String() string { return proto.CompactTextString(m) }
func (*StatusResponse_TmStatus) ProtoMessage()    {}
func (*StatusResponse_TmStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{2, 0}
}

func (m *StatusResponse_TmStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse_TmStatus.Unmarshal(m, b)
}
func (m *StatusResponse_TmStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse_TmStatus.Marshal(b, m, deterministic)
}
func (m *StatusResponse_TmStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse_TmStatus.Merge(m, src)
}
func (m *StatusResponse_TmStatus) XXX_Size() int {
	return xxx_messageInfo_StatusResponse_TmStatus.Size(m)
}
func (m *StatusResponse_TmStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse_TmStatus.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse_TmStatus proto.InternalMessageInfo

func (m *StatusResponse_TmStatus) GetNodeInfo() *NodeInfo {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

func (m *StatusResponse_TmStatus) GetSyncInfo() *StatusResponse_TmStatus_SyncInfo {
	if m != nil {
		return m.SyncInfo
	}
	return nil
}

func (m *StatusResponse_TmStatus) GetValidatorInfo() *StatusResponse_TmStatus_ValidatorInfo {
	if m != nil {
		return m.ValidatorInfo
	}
	return nil
}

type StatusResponse_TmStatus_SyncInfo struct {
	LatestBlockHash      string   `protobuf:"bytes,5,opt,name=latest_block_hash,json=latestBlockHash,proto3" json:"latest_block_hash"`
	LatestAppHash        string   `protobuf:"bytes,1,opt,name=latest_app_hash,json=latestAppHash,proto3" json:"latest_app_hash"`
	LatestBlockHeight    int64    `protobuf:"varint,2,opt,name=latest_block_height,json=latestBlockHeight,proto3" json:"latest_block_height"`
	LatestBlockTime      string   `protobuf:"bytes,3,opt,name=latest_block_time,json=latestBlockTime,proto3" json:"latest_block_time"`
	CatchingUp           bool     `protobuf:"varint,4,opt,name=catching_up,json=catchingUp,proto3" json:"catching_up"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse_TmStatus_SyncInfo) Reset()         { *m = StatusResponse_TmStatus_SyncInfo{} }
func (m *StatusResponse_TmStatus_SyncInfo) String() string { return proto.CompactTextString(m) }
func (*StatusResponse_TmStatus_SyncInfo) ProtoMessage()    {}
func (*StatusResponse_TmStatus_SyncInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{2, 0, 0}
}

func (m *StatusResponse_TmStatus_SyncInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse_TmStatus_SyncInfo.Unmarshal(m, b)
}
func (m *StatusResponse_TmStatus_SyncInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse_TmStatus_SyncInfo.Marshal(b, m, deterministic)
}
func (m *StatusResponse_TmStatus_SyncInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse_TmStatus_SyncInfo.Merge(m, src)
}
func (m *StatusResponse_TmStatus_SyncInfo) XXX_Size() int {
	return xxx_messageInfo_StatusResponse_TmStatus_SyncInfo.Size(m)
}
func (m *StatusResponse_TmStatus_SyncInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse_TmStatus_SyncInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse_TmStatus_SyncInfo proto.InternalMessageInfo

func (m *StatusResponse_TmStatus_SyncInfo) GetLatestBlockHash() string {
	if m != nil {
		return m.LatestBlockHash
	}
	return ""
}

func (m *StatusResponse_TmStatus_SyncInfo) GetLatestAppHash() string {
	if m != nil {
		return m.LatestAppHash
	}
	return ""
}

func (m *StatusResponse_TmStatus_SyncInfo) GetLatestBlockHeight() int64 {
	if m != nil {
		return m.LatestBlockHeight
	}
	return 0
}

func (m *StatusResponse_TmStatus_SyncInfo) GetLatestBlockTime() string {
	if m != nil {
		return m.LatestBlockTime
	}
	return ""
}

func (m *StatusResponse_TmStatus_SyncInfo) GetCatchingUp() bool {
	if m != nil {
		return m.CatchingUp
	}
	return false
}

type StatusResponse_TmStatus_ValidatorInfo struct {
	Address              string                                        `protobuf:"bytes,3,opt,name=address,proto3" json:"address"`
	PubKey               *StatusResponse_TmStatus_ValidatorInfo_PubKey `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key"`
	VotingPower          int64                                         `protobuf:"varint,2,opt,name=voting_power,json=votingPower,proto3" json:"voting_power"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *StatusResponse_TmStatus_ValidatorInfo) Reset()         { *m = StatusResponse_TmStatus_ValidatorInfo{} }
func (m *StatusResponse_TmStatus_ValidatorInfo) String() string { return proto.CompactTextString(m) }
func (*StatusResponse_TmStatus_ValidatorInfo) ProtoMessage()    {}
func (*StatusResponse_TmStatus_ValidatorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{2, 0, 1}
}

func (m *StatusResponse_TmStatus_ValidatorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo.Unmarshal(m, b)
}
func (m *StatusResponse_TmStatus_ValidatorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo.Marshal(b, m, deterministic)
}
func (m *StatusResponse_TmStatus_ValidatorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo.Merge(m, src)
}
func (m *StatusResponse_TmStatus_ValidatorInfo) XXX_Size() int {
	return xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo.Size(m)
}
func (m *StatusResponse_TmStatus_ValidatorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo proto.InternalMessageInfo

func (m *StatusResponse_TmStatus_ValidatorInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *StatusResponse_TmStatus_ValidatorInfo) GetPubKey() *StatusResponse_TmStatus_ValidatorInfo_PubKey {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *StatusResponse_TmStatus_ValidatorInfo) GetVotingPower() int64 {
	if m != nil {
		return m.VotingPower
	}
	return 0
}

type StatusResponse_TmStatus_ValidatorInfo_PubKey struct {
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type"`
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse_TmStatus_ValidatorInfo_PubKey) Reset() {
	*m = StatusResponse_TmStatus_ValidatorInfo_PubKey{}
}
func (m *StatusResponse_TmStatus_ValidatorInfo_PubKey) String() string {
	return proto.CompactTextString(m)
}
func (*StatusResponse_TmStatus_ValidatorInfo_PubKey) ProtoMessage() {}
func (*StatusResponse_TmStatus_ValidatorInfo_PubKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{2, 0, 1, 0}
}

func (m *StatusResponse_TmStatus_ValidatorInfo_PubKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo_PubKey.Unmarshal(m, b)
}
func (m *StatusResponse_TmStatus_ValidatorInfo_PubKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo_PubKey.Marshal(b, m, deterministic)
}
func (m *StatusResponse_TmStatus_ValidatorInfo_PubKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo_PubKey.Merge(m, src)
}
func (m *StatusResponse_TmStatus_ValidatorInfo_PubKey) XXX_Size() int {
	return xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo_PubKey.Size(m)
}
func (m *StatusResponse_TmStatus_ValidatorInfo_PubKey) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo_PubKey.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo_PubKey proto.InternalMessageInfo

func (m *StatusResponse_TmStatus_ValidatorInfo_PubKey) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *StatusResponse_TmStatus_ValidatorInfo_PubKey) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PruneBlocksRequest struct {
	FromHeight           int64    `protobuf:"varint,1,opt,name=from_height,json=fromHeight,proto3" json:"from_height"`
	ToHeight             int64    `protobuf:"varint,2,opt,name=to_height,json=toHeight,proto3" json:"to_height"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PruneBlocksRequest) Reset()         { *m = PruneBlocksRequest{} }
func (m *PruneBlocksRequest) String() string { return proto.CompactTextString(m) }
func (*PruneBlocksRequest) ProtoMessage()    {}
func (*PruneBlocksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{3}
}

func (m *PruneBlocksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PruneBlocksRequest.Unmarshal(m, b)
}
func (m *PruneBlocksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PruneBlocksRequest.Marshal(b, m, deterministic)
}
func (m *PruneBlocksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PruneBlocksRequest.Merge(m, src)
}
func (m *PruneBlocksRequest) XXX_Size() int {
	return xxx_messageInfo_PruneBlocksRequest.Size(m)
}
func (m *PruneBlocksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PruneBlocksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PruneBlocksRequest proto.InternalMessageInfo

func (m *PruneBlocksRequest) GetFromHeight() int64 {
	if m != nil {
		return m.FromHeight
	}
	return 0
}

func (m *PruneBlocksRequest) GetToHeight() int64 {
	if m != nil {
		return m.ToHeight
	}
	return 0
}

type DealPeerRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address"`
	Persistent           bool     `protobuf:"varint,2,opt,name=persistent,proto3" json:"persistent"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealPeerRequest) Reset()         { *m = DealPeerRequest{} }
func (m *DealPeerRequest) String() string { return proto.CompactTextString(m) }
func (*DealPeerRequest) ProtoMessage()    {}
func (*DealPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{4}
}

func (m *DealPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealPeerRequest.Unmarshal(m, b)
}
func (m *DealPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealPeerRequest.Marshal(b, m, deterministic)
}
func (m *DealPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealPeerRequest.Merge(m, src)
}
func (m *DealPeerRequest) XXX_Size() int {
	return xxx_messageInfo_DealPeerRequest.Size(m)
}
func (m *DealPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DealPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DealPeerRequest proto.InternalMessageInfo

func (m *DealPeerRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DealPeerRequest) GetPersistent() bool {
	if m != nil {
		return m.Persistent
	}
	return false
}

func init() {
	proto.RegisterType((*NodeInfo)(nil), "pb.NodeInfo")
	proto.RegisterType((*NodeInfo_ProtocolVersion)(nil), "pb.NodeInfo.ProtocolVersion")
	proto.RegisterType((*NodeInfo_Other)(nil), "pb.NodeInfo.Other")
	proto.RegisterType((*NetInfoResponse)(nil), "pb.NetInfoResponse")
	proto.RegisterType((*NetInfoResponse_Peer)(nil), "pb.NetInfoResponse.Peer")
	proto.RegisterType((*NetInfoResponse_Peer_ConnectionStatus)(nil), "pb.NetInfoResponse.Peer.ConnectionStatus")
	proto.RegisterType((*NetInfoResponse_Peer_ConnectionStatus_Monitor)(nil), "pb.NetInfoResponse.Peer.ConnectionStatus.Monitor")
	proto.RegisterType((*NetInfoResponse_Peer_ConnectionStatus_Channel)(nil), "pb.NetInfoResponse.Peer.ConnectionStatus.Channel")
	proto.RegisterType((*StatusResponse)(nil), "pb.StatusResponse")
	proto.RegisterType((*StatusResponse_TmStatus)(nil), "pb.StatusResponse.TmStatus")
	proto.RegisterType((*StatusResponse_TmStatus_SyncInfo)(nil), "pb.StatusResponse.TmStatus.SyncInfo")
	proto.RegisterType((*StatusResponse_TmStatus_ValidatorInfo)(nil), "pb.StatusResponse.TmStatus.ValidatorInfo")
	proto.RegisterType((*StatusResponse_TmStatus_ValidatorInfo_PubKey)(nil), "pb.StatusResponse.TmStatus.ValidatorInfo.PubKey")
	proto.RegisterType((*PruneBlocksRequest)(nil), "pb.PruneBlocksRequest")
	proto.RegisterType((*DealPeerRequest)(nil), "pb.DealPeerRequest")
}

func init() { proto.RegisterFile("manager.proto", fileDescriptor_cde9ec64f0d2c859) }

var fileDescriptor_cde9ec64f0d2c859 = []byte{
	// 1214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xd6, 0xda, 0x89, 0xbd, 0x3e, 0xce, 0xef, 0x14, 0x15, 0xb3, 0xa9, 0x68, 0x08, 0x15, 0x4a,
	0x11, 0xda, 0x82, 0x41, 0xc0, 0x0d, 0x17, 0x6e, 0x82, 0xa8, 0x55, 0xb5, 0x35, 0xeb, 0xd2, 0xdb,
	0xd5, 0x7a, 0x7d, 0x62, 0x8f, 0x62, 0xcf, 0x0c, 0xb3, 0xb3, 0x6e, 0xcd, 0x63, 0xf0, 0x18, 0x48,
	0x08, 0x89, 0xd7, 0xe0, 0x9a, 0x2b, 0xde, 0xa3, 0x12, 0x77, 0x68, 0xfe, 0x1c, 0x6f, 0xd2, 0x54,
	0x0d, 0x57, 0xde, 0xef, 0x3b, 0x33, 0x9f, 0xcf, 0xf9, 0x66, 0xcf, 0xd9, 0x81, 0xed, 0x79, 0xc6,
	0xb2, 0x09, 0xca, 0x58, 0x48, 0xae, 0x38, 0xa9, 0x89, 0x51, 0x74, 0x30, 0xe1, 0x7c, 0x32, 0xc3,
	0x07, 0x86, 0x19, 0x95, 0x67, 0x0f, 0x70, 0x2e, 0xd4, 0xd2, 0x2e, 0x38, 0xfa, 0xad, 0x0e, 0xe1,
	0x53, 0x3e, 0xc6, 0x3e, 0x3b, 0xe3, 0xe4, 0x07, 0xd8, 0x33, 0x6c, 0xce, 0x67, 0xe9, 0x02, 0x65,
	0x41, 0x39, 0xeb, 0x84, 0x87, 0xc1, 0x71, 0xbb, 0x7b, 0x27, 0x16, 0xa3, 0xd8, 0xaf, 0x8b, 0x07,
	0x6e, 0xd1, 0x0b, 0xbb, 0x26, 0xd9, 0x15, 0x55, 0x82, 0xec, 0x40, 0x8d, 0x8e, 0x3b, 0xc1, 0x61,
	0x70, 0xdc, 0x4a, 0x6a, 0x74, 0x4c, 0xee, 0x42, 0x7b, 0x46, 0x0b, 0x85, 0x2c, 0xcd, 0xc6, 0x63,
	0xd9, 0xa9, 0x99, 0x00, 0x58, 0xaa, 0x37, 0x1e, 0x4b, 0xd2, 0x81, 0x26, 0x43, 0xf5, 0x92, 0xcb,
	0xf3, 0x4e, 0xdd, 0x04, 0x3d, 0xd4, 0x11, 0x9f, 0xca, 0x86, 0x8d, 0x38, 0x48, 0x22, 0x08, 0xf3,
	0x69, 0xc6, 0x18, 0xce, 0x8a, 0xce, 0xa6, 0x09, 0xad, 0xb0, 0xde, 0x35, 0xe7, 0x8c, 0x9e, 0xa3,
	0xec, 0x34, 0xec, 0x2e, 0x07, 0xc9, 0x31, 0x6c, 0x72, 0x35, 0x45, 0xd9, 0x69, 0x9a, 0xc2, 0x48,
	0xa5, 0xb0, 0x67, 0x3a, 0x92, 0xd8, 0x05, 0xd1, 0x63, 0xd8, 0xbd, 0x54, 0x28, 0xd9, 0x83, 0xba,
	0xe8, 0x0a, 0x97, 0xa2, 0x7e, 0x24, 0xef, 0xc1, 0xe6, 0x68, 0xc6, 0xf3, 0x73, 0x57, 0xac, 0x05,
	0x7a, 0x5d, 0x26, 0x84, 0xab, 0x53, 0x3f, 0x46, 0x27, 0xb0, 0x69, 0xc4, 0xc9, 0x07, 0x10, 0xaa,
	0x57, 0x29, 0x65, 0x63, 0x7c, 0xe5, 0xe2, 0x4d, 0xf5, 0xaa, 0xaf, 0xa1, 0x76, 0x49, 0x8a, 0xdc,
	0x58, 0x84, 0x45, 0xe1, 0x14, 0x41, 0x8a, 0xbc, 0x67, 0x99, 0xa3, 0x5f, 0x5b, 0xb0, 0xfb, 0x14,
	0x95, 0x4e, 0x35, 0xc1, 0x42, 0x70, 0x56, 0x20, 0xb9, 0x03, 0x2d, 0xeb, 0x23, 0x65, 0x13, 0xe3,
	0x50, 0x98, 0x5c, 0x10, 0x17, 0x51, 0x94, 0x5a, 0xb0, 0x7e, 0xdc, 0x4a, 0x2e, 0x08, 0xf2, 0x3e,
	0x34, 0x59, 0x2a, 0x50, 0xc7, 0x6c, 0x2a, 0x0d, 0x36, 0xd0, 0x88, 0xc4, 0xb0, 0x69, 0xe9, 0xfa,
	0x61, 0xfd, 0xb8, 0xdd, 0xed, 0x18, 0x93, 0xaa, 0x7f, 0x1c, 0xeb, 0x95, 0x89, 0x5d, 0x16, 0xfd,
	0xdb, 0x84, 0x0d, 0x8d, 0xc9, 0x7d, 0x68, 0x31, 0x3e, 0xc6, 0x94, 0xb2, 0x33, 0x6e, 0xb2, 0x69,
	0x77, 0xb7, 0xd6, 0x1d, 0x4e, 0x42, 0xe6, 0x5f, 0xb6, 0xbb, 0xd0, 0xa6, 0x45, 0xca, 0x4b, 0x35,
	0xe2, 0x25, 0xb3, 0x2f, 0x4b, 0x98, 0x00, 0x2d, 0x9e, 0x39, 0x86, 0xbc, 0x80, 0xfd, 0x9c, 0x33,
	0x86, 0xb9, 0xa2, 0x9c, 0xa5, 0x85, 0xca, 0x54, 0x69, 0xf3, 0x6c, 0x77, 0xef, 0x5f, 0x97, 0x50,
	0x7c, 0xb2, 0xda, 0x31, 0x34, 0x1b, 0x92, 0xbd, 0xfc, 0x12, 0x43, 0x0e, 0xa0, 0x25, 0x71, 0xce,
	0x15, 0xa6, 0xd4, 0x1f, 0x65, 0x68, 0x89, 0xbe, 0x88, 0xfe, 0x68, 0xc0, 0xde, 0x65, 0x0d, 0xfd,
	0xa6, 0x9d, 0x96, 0x32, 0x53, 0x17, 0x2f, 0xe1, 0x0a, 0x93, 0x21, 0xb4, 0x87, 0xc8, 0xc6, 0x4f,
	0x38, 0xa3, 0x8a, 0x4b, 0x53, 0x46, 0xbb, 0xfb, 0xc5, 0x3b, 0xe7, 0x17, 0xbb, 0x8d, 0xc9, 0xba,
	0x8a, 0x16, 0x4d, 0x30, 0x5f, 0x78, 0xd1, 0xda, 0xff, 0x16, 0x5d, 0x53, 0x21, 0x4f, 0x20, 0x3c,
	0xf1, 0xfd, 0x62, 0xcf, 0xf5, 0x06, 0x8a, 0x6e, 0x67, 0xb2, 0x92, 0x88, 0xfe, 0xae, 0x41, 0xd3,
	0x4b, 0xdf, 0x86, 0x46, 0x2f, 0x57, 0x74, 0x81, 0x9d, 0x6d, 0x73, 0x8c, 0x0e, 0xe9, 0xee, 0x18,
	0xaa, 0x4c, 0x2a, 0xdf, 0x1d, 0x06, 0x54, 0xec, 0xac, 0x5d, 0xb2, 0x93, 0xc0, 0x46, 0x7f, 0x3c,
	0x43, 0x77, 0x2e, 0xe6, 0x59, 0xab, 0x3c, 0x5c, 0x2a, 0x2c, 0x9c, 0xf7, 0x16, 0xe8, 0x16, 0x1f,
	0x66, 0x73, 0x31, 0x43, 0xdf, 0xfd, 0x1e, 0x6a, 0xfd, 0x3e, 0x2b, 0x54, 0x92, 0x29, 0x74, 0xdd,
	0xbf, 0xc2, 0x7a, 0xd7, 0x49, 0x29, 0x4d, 0xa8, 0x69, 0x77, 0x39, 0xa8, 0x23, 0xbd, 0xc5, 0xc4,
	0x44, 0x42, 0x1b, 0x71, 0x50, 0xeb, 0x0d, 0x30, 0x3b, 0x37, 0xa1, 0x96, 0xd5, 0xf3, 0x58, 0xc7,
	0x4c, 0x3a, 0x09, 0xce, 0x3b, 0x60, 0x63, 0x1e, 0x6b, 0xc5, 0xe7, 0x74, 0x8e, 0x3a, 0xd4, 0xb6,
	0x8a, 0x0e, 0x1a, 0x45, 0xc9, 0x27, 0xa6, 0xcd, 0xb7, 0x0e, 0x83, 0xe3, 0x20, 0x59, 0xe1, 0xe8,
	0xf7, 0x00, 0x9a, 0xce, 0x64, 0x3d, 0x47, 0xfb, 0xa7, 0xa6, 0xbc, 0x20, 0xa9, 0xf5, 0x4f, 0xc9,
	0x67, 0xb0, 0xaf, 0x5f, 0x93, 0x1f, 0x4b, 0x2c, 0xf1, 0x24, 0x13, 0x59, 0x4e, 0xd5, 0xd2, 0x79,
	0x7b, 0x35, 0x40, 0xee, 0xc1, 0xf6, 0x8a, 0x1c, 0xd2, 0x5f, 0xd0, 0x99, 0x5d, 0x25, 0x6d, 0x2e,
	0x94, 0x4b, 0x2d, 0xe5, 0xba, 0xc1, 0x63, 0x72, 0x04, 0x5b, 0x09, 0xe6, 0xc8, 0xd4, 0x6c, 0x39,
	0x44, 0xa6, 0xdc, 0x01, 0x54, 0xb8, 0xa3, 0x3f, 0x9b, 0xb0, 0xe3, 0x7a, 0xcd, 0xcf, 0xa4, 0xb5,
	0x99, 0xdd, 0xac, 0xce, 0xec, 0x4f, 0x61, 0x7f, 0x96, 0x29, 0x2c, 0x54, 0x6a, 0x06, 0x65, 0x3a,
	0xcd, 0x8a, 0xa9, 0x2b, 0x60, 0xd7, 0x06, 0x1e, 0x6a, 0xfe, 0x51, 0x56, 0x4c, 0xc9, 0x27, 0xe0,
	0xa8, 0x34, 0x13, 0xc2, 0xae, 0x74, 0x05, 0x58, 0xba, 0x27, 0x84, 0x59, 0x17, 0xc3, 0xad, 0xaa,
	0x26, 0xd2, 0xc9, 0x54, 0x99, 0x5a, 0xea, 0xc9, 0xfe, 0xba, 0xaa, 0x09, 0x5c, 0xc9, 0x41, 0xd1,
	0x39, 0xba, 0xca, 0xd6, 0x73, 0xd0, 0x67, 0x45, 0x3e, 0x86, 0x6d, 0x3d, 0x78, 0x30, 0x9d, 0xd2,
	0x42, 0x71, 0xb9, 0x74, 0xaf, 0xda, 0x96, 0x21, 0x1f, 0x59, 0x8e, 0x7c, 0x0b, 0x2d, 0x35, 0xf7,
	0x03, 0xaa, 0x61, 0x7a, 0xf5, 0x40, 0x77, 0x56, 0xd5, 0x95, 0xf8, 0xf9, 0xdc, 0x11, 0xa1, 0x72,
	0x4f, 0xd1, 0xeb, 0x0d, 0x08, 0x3d, 0x5d, 0x9d, 0x9d, 0xf5, 0xb7, 0xce, 0xce, 0x1e, 0xb4, 0x8a,
	0x25, 0xcb, 0xed, 0x52, 0x3b, 0x72, 0xee, 0xbd, 0xe5, 0x1f, 0xe3, 0xe1, 0x92, 0xe5, 0x56, 0xa2,
	0x70, 0x4f, 0x64, 0x00, 0x3b, 0x8b, 0x6c, 0x46, 0xc7, 0x99, 0xe2, 0xd2, 0xea, 0xac, 0x8d, 0xd6,
	0xeb, 0x74, 0x5e, 0xf8, 0x1d, 0x46, 0x6c, 0x7b, 0xb1, 0x0e, 0xa3, 0x7f, 0x02, 0x08, 0xfd, 0x1f,
	0xbd, 0xf9, 0xa0, 0x37, 0xdf, 0xf9, 0xa0, 0x83, 0x1b, 0x1c, 0x74, 0xed, 0x46, 0x07, 0x5d, 0x7f,
	0xf3, 0x41, 0xdf, 0x85, 0x76, 0x9e, 0xa9, 0x7c, 0x4a, 0xd9, 0x24, 0x2d, 0x85, 0xfb, 0x90, 0x82,
	0xa7, 0x7e, 0x12, 0xd1, 0x5f, 0x01, 0x6c, 0x57, 0xca, 0xd7, 0x6f, 0xb9, 0xff, 0x54, 0xbb, 0x3b,
	0x8b, 0x83, 0xa4, 0x0f, 0x4d, 0x51, 0x8e, 0xd2, 0x73, 0x5c, 0xba, 0xc3, 0xf9, 0xfc, 0x9d, 0x4d,
	0x8d, 0x07, 0xe5, 0xe8, 0x31, 0x2e, 0x93, 0x86, 0x30, 0xbf, 0xe4, 0x23, 0xd8, 0x5a, 0x70, 0xa5,
	0xb3, 0x12, 0xfc, 0x25, 0x4a, 0x57, 0x6c, 0xdb, 0x72, 0x03, 0x4d, 0x45, 0x5d, 0x68, 0xd8, 0x4d,
	0x7a, 0x78, 0xaa, 0xa5, 0xf0, 0x7d, 0x6e, 0x9e, 0xf5, 0xf0, 0x5c, 0x64, 0xb3, 0x12, 0xfd, 0x08,
	0x36, 0xe0, 0x28, 0x01, 0x32, 0x90, 0x25, 0x43, 0x63, 0x40, 0x91, 0xe0, 0xcf, 0x25, 0x16, 0x4a,
	0x9b, 0x70, 0x26, 0xf9, 0xdc, 0x1b, 0x1b, 0x98, 0xff, 0x02, 0x4d, 0x39, 0x47, 0x0f, 0xa0, 0xa5,
	0x78, 0xd5, 0xf7, 0x50, 0x71, 0x1b, 0x3c, 0x7a, 0x0c, 0xbb, 0xa7, 0x98, 0xcd, 0xcc, 0xbd, 0xc0,
	0x09, 0xae, 0x59, 0x14, 0x54, 0x2d, 0xfa, 0x10, 0x40, 0xe8, 0x99, 0xa0, 0xaf, 0x22, 0x56, 0x2a,
	0x4c, 0xd6, 0x98, 0xee, 0xeb, 0x00, 0x76, 0x9e, 0xd8, 0xab, 0xec, 0x10, 0xe5, 0x82, 0xe6, 0x48,
	0xbe, 0x82, 0x86, 0xeb, 0x94, 0xdb, 0xb1, 0xbd, 0xd2, 0xc6, 0xfe, 0x4a, 0x1b, 0x7f, 0xaf, 0xaf,
	0xb4, 0x11, 0xb9, 0x6a, 0x33, 0xf9, 0x1a, 0x9a, 0xee, 0x0b, 0x77, 0xed, 0xb6, 0x5b, 0x6f, 0xf8,
	0x0c, 0x92, 0xef, 0xa0, 0xbd, 0xe6, 0x10, 0xb9, 0xad, 0xd7, 0x5c, 0xb5, 0x2c, 0xba, 0x46, 0x93,
	0x7c, 0x03, 0xa1, 0x37, 0x83, 0x18, 0xfd, 0x4b, 0xd6, 0x5c, 0xb7, 0x71, 0xd4, 0x30, 0xf8, 0xcb,
	0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x48, 0xf7, 0x53, 0xe9, 0xc9, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ManagerServiceClient is the client API for ManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagerServiceClient interface {
	Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	NetInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*NetInfoResponse, error)
	PruneBlocks(ctx context.Context, in *PruneBlocksRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DealPeer(ctx context.Context, in *DealPeerRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type managerServiceClient struct {
	cc *grpc.ClientConn
}

func NewManagerServiceClient(cc *grpc.ClientConn) ManagerServiceClient {
	return &managerServiceClient{cc}
}

func (c *managerServiceClient) Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/pb.ManagerService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) NetInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*NetInfoResponse, error) {
	out := new(NetInfoResponse)
	err := c.cc.Invoke(ctx, "/pb.ManagerService/NetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) PruneBlocks(ctx context.Context, in *PruneBlocksRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ManagerService/PruneBlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) DealPeer(ctx context.Context, in *DealPeerRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ManagerService/DealPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServiceServer is the server API for ManagerService service.
type ManagerServiceServer interface {
	Status(context.Context, *empty.Empty) (*StatusResponse, error)
	NetInfo(context.Context, *empty.Empty) (*NetInfoResponse, error)
	PruneBlocks(context.Context, *PruneBlocksRequest) (*empty.Empty, error)
	DealPeer(context.Context, *DealPeerRequest) (*empty.Empty, error)
}

// UnimplementedManagerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedManagerServiceServer struct {
}

func (*UnimplementedManagerServiceServer) Status(ctx context.Context, req *empty.Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (*UnimplementedManagerServiceServer) NetInfo(ctx context.Context, req *empty.Empty) (*NetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetInfo not implemented")
}
func (*UnimplementedManagerServiceServer) PruneBlocks(ctx context.Context, req *PruneBlocksRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PruneBlocks not implemented")
}
func (*UnimplementedManagerServiceServer) DealPeer(ctx context.Context, req *DealPeerRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DealPeer not implemented")
}

func RegisterManagerServiceServer(s *grpc.Server, srv ManagerServiceServer) {
	s.RegisterService(&_ManagerService_serviceDesc, srv)
}

func _ManagerService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ManagerService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).Status(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_NetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).NetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ManagerService/NetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).NetInfo(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_PruneBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PruneBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).PruneBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ManagerService/PruneBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).PruneBlocks(ctx, req.(*PruneBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_DealPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DealPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).DealPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ManagerService/DealPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).DealPeer(ctx, req.(*DealPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ManagerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ManagerService",
	HandlerType: (*ManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _ManagerService_Status_Handler,
		},
		{
			MethodName: "NetInfo",
			Handler:    _ManagerService_NetInfo_Handler,
		},
		{
			MethodName: "PruneBlocks",
			Handler:    _ManagerService_PruneBlocks_Handler,
		},
		{
			MethodName: "DealPeer",
			Handler:    _ManagerService_DealPeer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manager.proto",
}
